export default {
  CHANGE_VIEW: "CHANGE_VIEW",
  MAP_IS_READY: "MAP_IS_READY",
  SET_DEVICE_ID: "SET_DEVICE_ID",
  SET_INFO: "SET_INFO",
  SET_REGION: "SET_REGION",
  SET_PLACES: "SET_PLACES",
  SET_ERROR: "SET_ERROR",
  SET_TOKEN: "SET_TOKEN"
};
