export default {
  MAP_IS_READY: "MAP_IS_READY",
  SET_INFO: "SET_INFO",
  SET_REGION: "SET_REGION",
  SET_PLACES: "SET_PLACES",
  SET_ERROR: "SET_ERROR",
  SET_TOKEN: "SET_TOKEN",
  SET_VIEW: "SET_VIEW",
  FETCH_PLACES_REQUEST: "FETCH_REGION_REQUEST",
  FETCH_PLACES_FAILURE: "FETCH_REGION_FAILURE",
  FETCH_PLACES_SUCCESS: "FETCH_REGION_SUCCESS"
};
